/** RPG Maker MZ / MV and WOLF RPG Editor. */
import { describeSpec } from "./entries";
import { csv, pascal, type Adapter, type AdapterInput } from "./types";

/** `{"idle/d0/w0": "hero_idle_d0_w0", …}` */
const lookup = ({ entries }: AdapterInput) => Object.fromEntries(entries.map((e) => [e.id, e.name]));

function rpgmakerPlugin(input: AdapterInput, mz: boolean): string {
  const { spec } = input;
  const d = describeSpec(spec);
  const name = `NaiSprite_${pascal(spec.characterKey)}`;
  const varParams = [
    { key: "pose", label: "ポーズ / Pose" },
    ...d.axes.map((a) => ({ key: a.key, label: a.label })),
  ];
  const params = varParams.map((v) => ` * @param ${v.key}Variable
 * @text ${v.label} の変数
 * @desc この変数の値（0 から）で ${v.label} を選ぶ。0 = 変数を使わず先頭の段階。
 * @type variable
 * @default 0
 *`).join("\n");
  const mzCommand = mz ? ` * @command show
 * @text 立ち絵を表示
 * @arg pictureId
 * @type number
 * @min 1
 * @default 1
 * @arg x
 * @type number
 * @default 0
 * @arg y
 * @type number
 * @default 0
 *` : "";
  const register = mz
    ? `  PluginManager.registerCommand(NAME, "show", (args) => {
    NaiSprite.show(Number(args.pictureId), Number(args.x), Number(args.y));
  });`
    : `  const _pluginCommand = Game_Interpreter.prototype.pluginCommand;
  Game_Interpreter.prototype.pluginCommand = function(command, args) {
    _pluginCommand.call(this, command, args);
    // ${name} show <pictureId> <x> <y>
    if (command === NAME && args[0] === "show") {
      NaiSprite.show(Number(args[1] || 1), Number(args[2] || 0), Number(args[3] || 0));
    }
  };`;
  return `//=============================================================================
// ${name}.js — generated by NovelAI Desktop (差分制作)
//=============================================================================
/*:
 * @target ${mz ? "MZ" : "MV"}
 * @plugindesc ${spec.characterKey} の立ち絵差分を変数から選んで表示します。
 * @author NovelAI Desktop
 *
 * @help
 * 変数（ポーズ・各軸の段階番号、0 から）を設定して「立ち絵を表示」を実行すると、
 * 対応する img/pictures の画像をピクチャとして表示します。
 * スクリプトからは ${name}.name(poseIndex, [axisIndex, ...]) でファイル名を取得できます。
 * ${mz ? "" : `プラグインコマンド: ${name} show <ピクチャ番号> <x> <y>`}
 *
${params}
${mzCommand}
 */
(() => {
  "use strict";
  const NAME = "${name}";
  const P = PluginManager.parameters(NAME);
  const POSES = ${JSON.stringify(d.poses.map((p) => p.key))};
  const AXES = ${JSON.stringify(d.axes.map((a) => ({ key: a.key, levels: a.levels.map((l) => l.key) })))};
  const FILES = ${JSON.stringify(lookup(input))};
  const index = (key) => {
    const id = Number(P[key + "Variable"] || 0);
    return id > 0 ? $gameVariables.value(id) : 0;
  };
  const NaiSprite = {
    name(pose, levels) {
      const parts = [POSES[pose] ?? POSES[0]];
      AXES.forEach((axis, i) => parts.push(axis.levels[(levels || [])[i] || 0] ?? axis.levels[0]));
      return FILES[parts.join("/")] || "";
    },
    current() {
      return NaiSprite.name(index("pose"), AXES.map((a) => index(a.key)));
    },
    show(pictureId, x, y) {
      const file = NaiSprite.current();
      if (file) $gameScreen.showPicture(pictureId, file, 0, x, y, 100, 100, 255, 0);
    },
  };
  window[NAME] = NaiSprite;
${register}
})();
`;
}

export const rpgmakerAdapter = (mz: boolean): Adapter => (input) => ({
  images: input.entries.map((e) => ({ name: e.name, relPath: `img/pictures/${e.name}.png` })),
  texts: [{ relPath: `js/plugins/NaiSprite_${pascal(input.spec.characterKey)}.js`, content: rpgmakerPlugin(input, mz) }],
});

/** WOLF RPG Editor: pictures + a CSV (pose / axis numbers → file) for the user database. */
export const wolfAdapter: Adapter = (input) => {
  const { spec, entries } = input;
  const d = describeSpec(spec);
  const dir = `Data/Picture/${spec.characterKey}`;
  const header = ["ファイル名", "ポーズ番号", ...d.axes.map((a) => `${a.label}番号`), "ID"];
  const rows = entries.map((e) => [
    `Picture/${spec.characterKey}/${e.name}.png`,
    String(d.poses.findIndex((p) => p.key === e.poseKey)),
    ...d.axes.map((a) => String(a.levels.findIndex((l) => l.key === e.levels[a.key]))),
    e.id,
  ]);
  const readme = [
    `${spec.characterKey} の立ち絵差分（NovelAI Desktop で書き出し）`,
    "",
    `${spec.characterKey}_sprites.csv をユーザーデータベースに読み込むと、`,
    "ポーズ番号・各軸の番号の組み合わせから画像ファイル名を引けます。",
    "",
    `ポーズ: ${d.poses.map((p, i) => `${i}=${p.label}`).join(" / ")}`,
    ...d.axes.map((a) => `${a.label}: ${a.levels.map((l, i) => `${i}=${l.label}`).join(" / ")}`),
    "",
  ].join("\n");
  return {
    images: entries.map((e) => ({ name: e.name, relPath: `${dir}/${e.name}.png` })),
    texts: [
      { relPath: `${spec.characterKey}_sprites.csv`, content: csv([header, ...rows]) },
      { relPath: `${spec.characterKey}_README.txt`, content: readme },
    ],
  };
};
