/** Generic files, Unity, Godot, Unreal and web texture atlases (Phaser / PixiJS). */
import { describeSpec, type ExportEntry } from "./entries";
import { csv, json, pascal, type Adapter, type AdapterInput } from "./types";

function manifest({ spec, entries, layers, scale }: AdapterInput, file: (e: ExportEntry) => string) {
  return {
    generator: "NovelAI Desktop",
    ...describeSpec(spec),
    scale,
    layers,
    sprites: entries.map((e) => ({
      id: e.id,
      name: e.name,
      file: file(e),
      pose: e.poseKey,
      levels: e.levels,
      ...(layers && !e.isBase && e.baseName ? { base: e.baseName } : {}),
    })),
  };
}

function manifestCsv({ spec, entries, layers }: AdapterInput, file: (e: ExportEntry) => string) {
  const header = ["name", "file", "pose", ...spec.axes.map((a) => a.key), ...(layers ? ["base"] : [])];
  const rows = entries.map((e) => [
    e.name, file(e), e.poseKey, ...spec.axes.map((a) => e.levels[a.key]), ...(layers ? [e.isBase ? "" : e.baseName ?? ""] : []),
  ]);
  return csv([header, ...rows]);
}

export const genericAdapter: Adapter = (input) => {
  const file = (e: ExportEntry) => `sprites/${e.name}.png`;
  return {
    images: input.entries.map((e) => ({ name: e.name, relPath: file(e) })),
    texts: [
      { relPath: "manifest.json", content: json(manifest(input, file)) },
      { relPath: "manifest.csv", content: manifestCsv(input, file) },
    ],
  };
};

export const unityAdapter: Adapter = (input) => {
  const cls = pascal(input.spec.characterKey);
  const dir = `Assets/NaiSprites/${cls}`;
  const file = (e: ExportEntry) => `${e.name}.png`;
  const cs = `// Generated by NovelAI Desktop (差分制作).
// Put this on a GameObject, assign the manifest (${input.spec.characterKey}.json) and the sprites
// (all ${cls}/*.png, imported as Sprite). Then: library.Get("${input.entries[0]?.id ?? "pose/level"}")
using System;
using System.Collections.Generic;
using UnityEngine;

public class NaiSpriteLibrary : MonoBehaviour
{
    [Serializable] class Entry { public string id; public string name; }
    [Serializable] class Manifest { public Entry[] sprites; }

    public TextAsset manifest;
    public Sprite[] sprites;
    Dictionary<string, Sprite> byId;

    void Awake()
    {
        var names = new Dictionary<string, Sprite>();
        foreach (var s in sprites) if (s != null) names[s.name] = s;
        byId = new Dictionary<string, Sprite>();
        foreach (var e in JsonUtility.FromJson<Manifest>(manifest.text).sprites)
            if (names.TryGetValue(e.name, out var s)) byId[e.id] = s;
    }

    /// <summary>Sprite by id: pose key and level keys joined with "/" in axis order.</summary>
    public Sprite Get(string id) => byId != null && byId.TryGetValue(id, out var s) ? s : null;

    public Sprite Get(string pose, params string[] levels) => Get(pose + (levels.Length > 0 ? "/" + string.Join("/", levels) : ""));
}
`;
  return {
    images: input.entries.map((e) => ({ name: e.name, relPath: `${dir}/${file(e)}` })),
    texts: [
      { relPath: `${dir}/${input.spec.characterKey}.json`, content: json(manifest(input, file)) },
      { relPath: "Assets/NaiSprites/NaiSpriteLibrary.cs", content: cs },
    ],
  };
};

export const godotAdapter: Adapter = (input) => {
  const c = input.spec.characterKey;
  const dir = `sprites/${c}`;
  const res = (e: ExportEntry) => `res://${dir}/${e.name}.png`;
  const entries = input.entries.map((e) => `\t"${e.id}": "${res(e)}",`).join("\n");
  const gd = `# Generated by NovelAI Desktop (差分制作).
# var tex := preload("res://${dir}/${c}_sprites.gd").get_texture("${input.entries[0]?.id ?? "pose/level"}")
extends RefCounted

const FILES := {
${entries}
}

## Texture by id: the pose key and level keys joined with "/" in axis order.
static func get_texture(id: String) -> Texture2D:
\treturn load(FILES[id]) if FILES.has(id) else null
`;
  return {
    images: input.entries.map((e) => ({ name: e.name, relPath: `${dir}/${e.name}.png` })),
    texts: [{ relPath: `${dir}/${c}_sprites.gd`, content: gd }],
  };
};

/** Unreal: textures + a DataTable CSV (row name = sprite name). */
export const unrealAdapter: Adapter = (input) => {
  const cls = pascal(input.spec.characterKey);
  const dir = `Sprites/${cls}`;
  const header = ["---", "Id", "Pose", ...input.spec.axes.map((a) => pascal(a.key)), "Texture"];
  const rows = input.entries.map((e) => [
    e.name, e.id, e.poseKey, ...input.spec.axes.map((a) => e.levels[a.key]), `/Game/${dir}/${e.name}.${e.name}`,
  ]);
  return {
    images: input.entries.map((e) => ({ name: e.name, relPath: `${dir}/${e.name}.png` })),
    texts: [{ relPath: `${dir}/DT_${cls}.csv`, content: csv([header, ...rows]) }],
  };
};

/** Phaser / PixiJS: trimmed frames in TexturePacker "JSON Hash" atlases + the manifest. */
export const webAtlasAdapter: Adapter = (input) => ({
  images: [],
  atlas: { name: input.spec.characterKey, relDir: "atlas" },
  texts: [{ relPath: "manifest.json", content: json(manifest(input, (e) => `atlas#${e.name}`)) }],
});
